name: _bazel_codegen
description: Bazel code generation runner
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/bazel
version: 0.0.3

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  analyzer: ^0.29.5
  args: ^0.13.6
  bazel_worker: ^0.1.2
  build: ^0.7.2
  build_barback: ^0.1.0
  logging: ^0.11.3
  path: ^1.4.1

dev_dependencies:
  test: ^0.12.15+2
